---
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: check-added-large-files
      - id: check-docstring-first
      - id: check-merge-conflict
      - id: end-of-file-fixer
  - repo: https://github.com/ambv/black
    rev: 22.12.0
    hooks:
      - id: black
        language_version: python3.7
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.910
    hooks:
      - name: Run mypy static analysis tool
        id: mypy
        files: src
        additional_dependencies:
          - pydantic
        args:
          - --no-warn-unused-ignores
          - --ignore-missing-imports
          # Only in this pre-commit hook, it is necessary to set this argument, it is working as intended in the normal `pdm run mypy` run:
          # mypy doesn't pick up the pyproject.toml configuration in the pre-commit hook, which already has this option enabled
          - --allow-untyped-decorators
          # Only in this pre-commit hook, it is working as intended in the normal `pdm run mypy` run:
          # mypy doesn't recognize the ConfigSchema type and gives the error
          # Class cannot subclass "ConfigSchema" (has type "Any")
          - --allow-subclassing-any
  - repo: https://github.com/flakeheaven/flakeheaven
    rev: 3.2.1
    hooks:
      - name: Run flakeheaven static analysis tool
        id: flakeheaven
        files: ^(src|tests)/.+?\.(ipynb|md|py|rst|yaml|yml)$
